services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"          # LocalStack edge port
      - "4571:4571"
    environment:
      - SERVICES=lambda,sqs,apigateway,s3,cloudwatch,events,cloudformation,iam,sts,logs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_data:/var/lib/localstack/data"
